### ISSUE TITLE
Error when attempting to haste a file or piped input

### ISSUE THREAD

**Issue by Justinzobel** [jirutka/haste-client#3]
haste --version
haste 1.0.2

Traceback (most recent call last):
  File "/usr/bin/haste", line 110, in <module>
    main(**kwargs)
  File "/usr/bin/haste", line 46, in main
    url = create_snippet(data, config['server_url'], config['timeout'], kwargs['--raw'])
  File "/usr/bin/haste", line 61, in create_snippet
    dockey = json.loads(response.text)['key']
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by diwu1989** [comment]
fixed by https://github.com/jirutka/haste-client/pull/4

**Comment by Justinzobel** [comment]
Excellent, thanks!
